#ifndef CONFIG_TEMPLATE_H
#define CONFIG_TEMPLATE_H

#include <stddef.h>

static const char CONFIG_TEMPLATE[] =
    "# rain configuration\n"
    "\n"
    "\n"
    "\n"
    "# =============================================================================\n"
    "# Colors\n"
    "# =============================================================================\n"
    "\n"
    "# Palette mode:\n"
    "#   auto    Generate a gradient from color_base.\n"
    "#   manual  Use the explicit colors list below.\n"
    "color_mode = manual\n"
    "\n"
    "# Base color for auto mode.\n"
    "# Format: #rrggbb\n"
    "# color_base = #ffffff\n"
    "\n"
    "# Manual color palette.\n"
    "#\n"
    "# Defining this key implicitly enables:\n"
    "#   color_mode = manual\n"
    "#\n"
    "# The list must contain exactly speed_max colors, brightest first\n"
    "# Format: #rrggbb, #rrggbb, ...\n"
    "colors = #ffffff, #949494, #686868, #464646, #393838\n"
    "\n"
    "# Color backend:\n"
    "#   false  Use init_color for exact RGB colors.\n"
    "#          Works in ghostty, kitty, wezterm, xterm and alacritty.\n"
    "#\n"
    "#   true   Quantize colors to the built-in xterm-256 palette.\n"
    "#          Use this for terminals that report color-changing support but\n"
    "#          ignore custom RGB palette changes, such as konsole or some\n"
    "#          SSH/tmux setups.\n"
    "# use_xterm256 = false\n"
    "\n"
    "\n"
    "\n"
    "# =============================================================================\n"
    "# Timing\n"
    "# =============================================================================\n"
    "\n"
    "# Delay between frames, in milliseconds.\n"
    "# Lower values make the rain faster.\n"
    "frame_delay_ms = 30\n"
    "\n"
    "\n"
    "# =============================================================================\n"
    "# Density and speed\n"
    "# =============================================================================\n"
    "\n"
    "# Horizontal drop density, measured as drops per terminal column.\n"
    "# density = 1.5\n"
    "\n"
    "# Drop speed range, measured in rows per frame.\n"
    "# speed_min must be less than or equal to speed_max.\n"
    "#\n"
    "# Drop shape depends on speed:\n"
    "#   speed < 3   -> |\n"
    "#   speed >= 3  -> :\n"
    "speed_min = 1\n"
    "speed_max = 5\n"
    "\n"
    "\n"
    "\n"
    "# =============================================================================\n"
    "# Input\n"
    "# =============================================================================\n"
    "\n"
    "# Quit key. Must be a single character.\n"
    "quit_key = q\n"
    "\n"
;

static const size_t CONFIG_TEMPLATE_LEN = sizeof(CONFIG_TEMPLATE) - 1;

#endif